### ISSUE TITLE
What is the purpose of mapping x to 10/85ths of it's value in SineWave?

### ISSUE THREAD

**Issue by dalton** [dagda1/d3-geometry#1]
https://github.com/dagda1/d3-geometry/blob/1f8fa44f8f856fd3e631a1722b485292af87c248/client/app/components/SineWave/SineWave.js#L244

I removed this line and it produces a trippy effect. I'm curious how you come to these values.

**Comment by dagda1** [comment]
Hi @dalton it's a few years since I wrote this but I think it was just trial and error to get the next  x coordinate.  I'm not entirely sure how scientific they are but I'm just getting the next x within what I consider reasonable bounds.

**Comment by dagda1** [comment]
@dalton I blogged about it [here](http://www.thesoftwaresimpleton.com/blog/2016/05/25/sine-wave/)

**Comment by dalton** [comment]
Thanks! Appreciate you making this project public. I've learned a lot about both D3 and React just by going through your examples.
